version: 2

base: &base
  machine:
    image: circleci/classic:latest
    docker_layer_caching: false

test: &test
  <<: *base
  steps:
    - checkout:
        path: ~/pandahouse
    - run:
        name: Start Clickhouse
        command: docker-compose up -d --no-build clickhouse
    - run:
        name: Build Pandahouse Image
        command: docker-compose build pandahouse
    - run:
        name: Run Tests
        command: docker-compose run pandahouse

jobs:
  python27_test:
    <<: *test
    environment:
      - PYTHON_VERSION: 3.5

  python35_test:
    <<: *test
    environment:
      - PYTHON_VERSION: 3.5

  python36_test:
    <<: *test
    environment:
      - PYTHON_VERSION: 3.6

workflows:
  version: 2
  test:
    jobs:
      - python27_test
      - python35_test
      - python36_test
