version: 2

test: &test
  machine:
    image: circleci/classic:latest
    # docker_layer_caching: false
  steps:
    - checkout
    - docker-compose up -d --no-build clickhouse
    - docker-compose build pandahouse
    - docker-compose run pandahouse

jobs:
  python27_test:
    <<: *test
    environment:
      - PYTHON_VERSION: 3.5

  python35_test:
    <<: *test
    environment:
      - PYTHON_VERSION: 3.5

  python36_test:
    <<: *test
    environment:
      - PYTHON_VERSION: 3.6

workflows:
  version: 2
  test:
    jobs:
      - python27_test
      - python35_test
      - python36_test
